export const Levels = { 
    HIGH: 'HIGH',
    MEDIUM: 'MEDIUM',
    NORMAL: 'NORMAL',
    NO_URGENTE: 'NO_URGENTE',
    NO_IMPORTANTE: 'NO_IMPORTANTE',
    NO_NORMAL: 'NO_NORMAL',
    BLOCKING: 'BLOCKING'
}