export const Levels = { 
    URGENTE: 'URGENTE',
    IMPORTANTE: 'IMPORTANTE',
    NORMAL: 'NORMAL',
    NO_URGENTE: 'NO_URGENTE',
    NO_IMPORTANTE: 'NO_IMPORTANTE',
    NO_NORMAL: 'NO_NORMAL',
    BLOCKING: 'BLOCKING'
}